project:
  type: website

website:
  title: "Chessmate Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Overview"
        contents:
          - index.qmd
          - CHESSMATE_FOR_DUMMIES.md
          - IMPLEMENTATION_PLAN.md
      - section: "Architecture & Ops"
        contents:
          - ARCHITECTURE.md
          - OPERATIONS.md
          - TROUBLESHOOTING.md
      - section: "Team Practices"
        contents:
          - DEVELOPER.md
          - GUIDELINES.md
          - PROMPTS.md

filters:
  - mermaid
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    mermaid: true
